gcloud run deploy agro-system \
  --source . \
  --region us-central1 \
  --platform managed \
  --allow-unauthenticated \
  --add-cloudsql-instances agro-system-app:us-central1:agro-db \
  --set-env-vars SECRET_KEY="agro4512meri" \
  --set-env-vars MYSQL_HOST="/cloudsql/agro-system-app:us-central1:agro-db" \
  --set-env-vars MYSQL_USER="root" \
  --set-env-vars MYSQL_PASSWORD="Usman$5000" \
  --set-env-vars MYSQL_DB="agrosystem" \
  --set-env-vars MYSQL_PORT="3306" \
  --set-env-vars MAIL_USERNAME="mu4512222@gmail.com" \
  --set-env-vars MAIL_PASSWORD="jdry inob yitt pasw" \
  --set-env-vars MAIL_DEFAULT_SENDER="Agro System <mu4512222@gmail.com>" \
  --set-env-vars ADMIN_EMAIL="mu4512222@gmail.com" \
  --set-env-vars JAZZCASH_NUMBER="03214512624" \
  --set-env-vars EASYPAISA_NUMBER="03131631965" \
  --set-env-vars OWNER_NAME="M Usman Manzoor"